spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mall
  jackson:
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
    mapper:
      accept-case-insensitive-enums: true
    generator:
      ignore-unknown: true
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  application:
    name: Mall-Foundry-APP
  cache:
    type: simple
  messages:
    basename: messages
  elasticsearch:
    rest:
      uris: http://localhost:9200
server:
  port: 8077
  error:
    include-message: always
  address: 0.0.0.0
springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    display-request-duration: true