logging:
  level:
    org.mallfoundry: debug
    #    org.hibernate: debug
    org.springframework.web: debug
    org.springframework.jdbc: debug
    org.springframework.transaction: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true