spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mall
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
  application:
    name: Mall-Fundory-APP
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-handlers-package: com.mallfoundry.mybatis.type
server:
  port: 8077
mall:
  storage:
    store:
      type: local
      directory: D:/mall/data/storage/
    http:
      base-url: http://localhost:${server.port}/static
  store:
    product:
      search:
        type: lucene
        lucene:
          directory: D:/mall/data/indexes