logging:
  level:
    com.mallfoundry: debug
    org.apache.ibatis: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true