spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mall
  jackson:
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
    mapper:
      accept-case-insensitive-enums: true
  profiles:
    active: dev
  application:
    name: Mall-Foundry-APP
server:
  port: 8077
  tomcat:
    max-threads: 200
    min-spare-threads: 20