spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mall
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-handlers-package: com.github.mall.mybatis.type
server:
  port: 8077