spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/shop
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-handlers-package: com.github.shop.mybatis.type
server:
  port: 8077
shop:
  storage:
    store:
      type: local
      directory: D:/shop/data/storage/
    http:
      base-url: http://localhost:${server.port}/static
  product:
    search:
      type: lucene
      lucene:
        directory: D:/shop/data/indexes